[tool.poetry]
name = "configvlm"
version = "0.1.0"
description = ""
authors = ["Leonard Hackel <l.hackel@tu-berlin.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
